"""initial schema from existing models

Revision ID: 5b8fc5b8972b
Revises: 
Create Date: 2026-03-09 13:58:12.796173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8fc5b8972b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boq_standard_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standard_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('standard_unit', sa.String(length=50), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('chapter', sa.String(length=100), nullable=False),
    sa.Column('measurement_rule', sa.Text(), nullable=False),
    sa.Column('common_characteristics', sa.Text(), nullable=False),
    sa.Column('standard_version', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('standard_code')
    )
    op.create_table('quota_resource_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quota_item_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('resource_code', sa.String(length=100), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('spec', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('is_main_material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quota_item_id'], ['quota_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qrd_category', 'quota_resource_details', ['category'], unique=False)
    op.create_index('ix_qrd_quota_item_id', 'quota_resource_details', ['quota_item_id'], unique=False)
    op.create_table('quota_resource_material_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_detail_id', sa.Integer(), nullable=False),
    sa.Column('material_price_id', sa.Integer(), nullable=False),
    sa.Column('match_method', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['material_price_id'], ['material_prices.id'], ),
    sa.ForeignKeyConstraint(['resource_detail_id'], ['quota_resource_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qrmm_material_price_id', 'quota_resource_material_mappings', ['material_price_id'], unique=False)
    op.create_index('ix_qrmm_resource_detail_id', 'quota_resource_material_mappings', ['resource_detail_id'], unique=False)
    op.create_index('ix_binding_boq_item_id', 'line_item_quota_bindings', ['boq_item_id'], unique=False)
    op.create_index('ix_binding_quota_item_id', 'line_item_quota_bindings', ['quota_item_id'], unique=False)
    op.create_unique_constraint('uq_boq_quota_binding', 'line_item_quota_bindings', ['boq_item_id', 'quota_item_id'])
    op.alter_column('material_prices', 'effective_date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.create_index('ix_material_price_lookup', 'material_prices', ['name', 'region', 'effective_date'], unique=False)
    op.add_column('quota_items', sa.Column('work_content', sa.Text(), nullable=False))
    op.add_column('quota_items', sa.Column('applicable_scope', sa.Text(), nullable=False))
    op.add_column('quota_items', sa.Column('chapter', sa.String(length=100), nullable=False))
    op.add_column('quota_items', sa.Column('version', sa.String(length=50), nullable=False))
    op.add_column('quota_items', sa.Column('base_price', sa.Float(), nullable=False))
    op.add_column('quota_items', sa.Column('has_resource_details', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quota_items', 'has_resource_details')
    op.drop_column('quota_items', 'base_price')
    op.drop_column('quota_items', 'version')
    op.drop_column('quota_items', 'chapter')
    op.drop_column('quota_items', 'applicable_scope')
    op.drop_column('quota_items', 'work_content')
    op.drop_index('ix_material_price_lookup', table_name='material_prices')
    op.alter_column('material_prices', 'effective_date',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.drop_constraint('uq_boq_quota_binding', 'line_item_quota_bindings', type_='unique')
    op.drop_index('ix_binding_quota_item_id', table_name='line_item_quota_bindings')
    op.drop_index('ix_binding_boq_item_id', table_name='line_item_quota_bindings')
    op.drop_index('ix_qrmm_resource_detail_id', table_name='quota_resource_material_mappings')
    op.drop_index('ix_qrmm_material_price_id', table_name='quota_resource_material_mappings')
    op.drop_table('quota_resource_material_mappings')
    op.drop_index('ix_qrd_quota_item_id', table_name='quota_resource_details')
    op.drop_index('ix_qrd_category', table_name='quota_resource_details')
    op.drop_table('quota_resource_details')
    op.drop_table('boq_standard_codes')
    # ### end Alembic commands ###
